// GENERATED from app/src/test/resources/fixtures/phase0_route_labels.jsonl
// (Phase 0 Jev labeling of the seed corpus — frozen gate fixture).
// Regenerate with: python tools/jev_harness/gen_kotlin_fixture.py
// Do not hand-edit.
package com.vyze.app.agent.student

/**
 * Frozen Phase 0 route labels: regex baseline, Jev (teacher), and the
 * hand-assigned expected action per seed query. Consumed by
 * StudentRouterFixtureTest to prove the student router meets the
 * Phase 2→3 gate (student ≥ regex baseline on this corpus).
 */
object StudentRouterFixture {

    data class Row(
        val id: String,
        val lang: String,
        val query: String,
        val previous: String?,
        val expected: String,
        val regexAction: String,
        val jevAction: String,
        val jevConfidence: Double,
        val jevFastPathNoul: Double,
    )

    val ROWS: List<Row> = listOf(
        Row(
            id = "p1",
            lang = "en",
            query = "What does this medicine label say?",
            previous = null,
            expected = "VLM_TEXT_READ",
            regexAction = "VLM_TEXT_READ",
            jevAction = "VLM_TEXT_READ",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.48,
        ),
        Row(
            id = "p2",
            lang = "en",
            query = "Describe the entire room in front of me.",
            previous = null,
            expected = "VLM_SCENE_DESCRIBE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_SCENE_DESCRIBE",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.05,
        ),
        Row(
            id = "p3",
            lang = "en",
            query = "Is the door on my left or right?",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_VOICE_QUERY",
            jevConfidence = 0.95,
            jevFastPathNoul = 0.1,
        ),
        Row(
            id = "p4",
            lang = "en",
            query = "Give me a double tap vibration.",
            previous = null,
            expected = "IGNORE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "none_of_these",
            jevConfidence = 0.45,
            jevFastPathNoul = 0.92,
        ),
        Row(
            id = "p5",
            lang = "en",
            query = "Help, I fell down and need assistance!",
            previous = null,
            expected = "SOS",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "SOS",
            jevConfidence = 0.94,
            jevFastPathNoul = 0.39,
        ),
        Row(
            id = "e1",
            lang = "en",
            query = "Read this letter for me.",
            previous = null,
            expected = "VLM_TEXT_READ",
            regexAction = "VLM_TEXT_READ",
            jevAction = "VLM_TEXT_READ",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.68,
        ),
        Row(
            id = "e2",
            lang = "en",
            query = "What color is this shirt?",
            previous = null,
            expected = "FAST_COLOR_ANALYSIS",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "FAST_COLOR_ANALYSIS",
            jevConfidence = 0.97,
            jevFastPathNoul = 0.38,
        ),
        Row(
            id = "e3",
            lang = "en",
            query = "Is it dark in here?",
            previous = null,
            expected = "LIGHT_CHECK",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "LIGHT_CHECK",
            jevConfidence = 0.99,
            jevFastPathNoul = 0.77,
        ),
        Row(
            id = "e4",
            lang = "en",
            query = "What is in front of me?",
            previous = null,
            expected = "VLM_SCENE_DESCRIBE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_SCENE_DESCRIBE",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.1,
        ),
        Row(
            id = "e5",
            lang = "en",
            query = "Play some music.",
            previous = null,
            expected = "IGNORE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "IGNORE",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.85,
        ),
        Row(
            id = "e6",
            lang = "en",
            query = "How much money is this banknote?",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_VOICE_QUERY",
            jevConfidence = 0.98,
            jevFastPathNoul = 0.59,
        ),
        Row(
            id = "a1",
            lang = "en",
            query = "Is someone standing near me?",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_VOICE_QUERY",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.08,
        ),
        Row(
            id = "a2",
            lang = "en",
            query = "Can you tell what this fruit is?",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_VOICE_QUERY",
            jevConfidence = 0.87,
            jevFastPathNoul = 0.06,
        ),
        Row(
            id = "a3",
            lang = "en",
            query = "Is this the exit sign?",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_TEXT_READ",
            jevAction = "VLM_TEXT_READ",
            jevConfidence = 0.46,
            jevFastPathNoul = 0.41,
        ),
        Row(
            id = "a4",
            lang = "en",
            query = "Is my bus number showing on that board?",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_TEXT_READ",
            jevConfidence = 0.85,
            jevFastPathNoul = 0.39,
        ),
        Row(
            id = "a5",
            lang = "en",
            query = "Does this look spoiled?",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_VOICE_QUERY",
            jevConfidence = 0.93,
            jevFastPathNoul = 0.13,
        ),
        Row(
            id = "a6",
            lang = "en",
            query = "Is there a chair I can sit on?",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_VOICE_QUERY",
            jevConfidence = 0.91,
            jevFastPathNoul = 0.07,
        ),
        Row(
            id = "a7",
            lang = "en",
            query = "Check if this bill is a fifty.",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_VOICE_QUERY",
            jevConfidence = 0.86,
            jevFastPathNoul = 0.66,
        ),
        Row(
            id = "m1",
            lang = "ms",
            query = "Baca label ubat ini.",
            previous = null,
            expected = "VLM_TEXT_READ",
            regexAction = "VLM_TEXT_READ",
            jevAction = "VLM_TEXT_READ",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.61,
        ),
        Row(
            id = "m2",
            lang = "ms",
            query = "Apa warna baju ini?",
            previous = null,
            expected = "FAST_COLOR_ANALYSIS",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "FAST_COLOR_ANALYSIS",
            jevConfidence = 0.98,
            jevFastPathNoul = 0.41,
        ),
        Row(
            id = "m3",
            lang = "ms",
            query = "Gelap ke di sini?",
            previous = null,
            expected = "LIGHT_CHECK",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "LIGHT_CHECK",
            jevConfidence = 0.99,
            jevFastPathNoul = 0.75,
        ),
        Row(
            id = "m4",
            lang = "ms",
            query = "Apa kat depan saya?",
            previous = null,
            expected = "VLM_SCENE_DESCRIBE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_SCENE_DESCRIBE",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.12,
        ),
        Row(
            id = "m5",
            lang = "ms",
            query = "Ada orang dekat dengan saya ke?",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_VOICE_QUERY",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.11,
        ),
        Row(
            id = "m6",
            lang = "ms",
            query = "Nota ini berapa ringgit?",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_VOICE_QUERY",
            jevConfidence = 0.98,
            jevFastPathNoul = 0.39,
        ),
        Row(
            id = "m7",
            lang = "ms",
            query = "Adakah buah ini masak?",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_VOICE_QUERY",
            jevConfidence = 0.96,
            jevFastPathNoul = 0.19,
        ),
        Row(
            id = "m8",
            lang = "ms",
            query = "Pintu tu di kiri atau kanan saya?",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_VOICE_QUERY",
            jevConfidence = 0.82,
            jevFastPathNoul = 0.13,
        ),
        Row(
            id = "m9",
            lang = "ms",
            query = "Putar lagu sikit.",
            previous = null,
            expected = "IGNORE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "IGNORE",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.81,
        ),
        Row(
            id = "m10",
            lang = "ms",
            query = "Tolong, saya jatuh! Saya tak boleh bangun.",
            previous = null,
            expected = "SOS",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "SOS",
            jevConfidence = 0.92,
            jevFastPathNoul = 0.48,
        ),
        Row(
            id = "ma1",
            lang = "ms",
            query = "Papan tanda tu tulis apa?",
            previous = null,
            expected = "VLM_TEXT_READ",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_TEXT_READ",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.52,
        ),
        Row(
            id = "ma2",
            lang = "ms",
            query = "Boleh tak you tengok jalan ni ada kereta?",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_VOICE_QUERY",
            jevConfidence = 0.97,
            jevFastPathNoul = 0.06,
        ),
        Row(
            id = "z1",
            lang = "zh",
            query = "帮我读一读这个药瓶上的标签。",
            previous = null,
            expected = "VLM_TEXT_READ",
            regexAction = "VLM_TEXT_READ",
            jevAction = "VLM_TEXT_READ",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.52,
        ),
        Row(
            id = "z2",
            lang = "zh",
            query = "这件衣服是什么颜色？",
            previous = null,
            expected = "FAST_COLOR_ANALYSIS",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "FAST_COLOR_ANALYSIS",
            jevConfidence = 0.95,
            jevFastPathNoul = 0.3,
        ),
        Row(
            id = "z3",
            lang = "zh",
            query = "这里是不是很暗？",
            previous = null,
            expected = "LIGHT_CHECK",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "LIGHT_CHECK",
            jevConfidence = 0.99,
            jevFastPathNoul = 0.76,
        ),
        Row(
            id = "z4",
            lang = "zh",
            query = "我面前是什么？",
            previous = null,
            expected = "VLM_SCENE_DESCRIBE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_SCENE_DESCRIBE",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.1,
        ),
        Row(
            id = "z5",
            lang = "zh",
            query = "有人站在我旁边吗？",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_VOICE_QUERY",
            jevConfidence = 0.99,
            jevFastPathNoul = 0.09,
        ),
        Row(
            id = "z6",
            lang = "zh",
            query = "这张钞票是多少钱？",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_VOICE_QUERY",
            jevConfidence = 0.98,
            jevFastPathNoul = 0.5,
        ),
        Row(
            id = "z7",
            lang = "zh",
            query = "这水果熟了没有？",
            previous = null,
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_VOICE_QUERY",
            jevConfidence = 0.96,
            jevFastPathNoul = 0.16,
        ),
        Row(
            id = "z8",
            lang = "zh",
            query = "放一首歌来听。",
            previous = null,
            expected = "IGNORE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "IGNORE",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.82,
        ),
        Row(
            id = "z9",
            lang = "zh",
            query = "救命，我摔倒了，起不来！",
            previous = null,
            expected = "SOS",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "SOS",
            jevConfidence = 0.97,
            jevFastPathNoul = 0.52,
        ),
        Row(
            id = "f1",
            lang = "en",
            query = "What is in front of me?",
            previous = null,
            expected = "VLM_SCENE_DESCRIBE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_SCENE_DESCRIBE",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.1,
        ),
        Row(
            id = "f2",
            lang = "en",
            query = "What about this?",
            previous = "What is in front of me?",
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_SCENE_DESCRIBE",
            jevConfidence = 0.9,
            jevFastPathNoul = 0.12,
        ),
        Row(
            id = "f3",
            lang = "ms",
            query = "Apa kat depan saya?",
            previous = null,
            expected = "VLM_SCENE_DESCRIBE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_SCENE_DESCRIBE",
            jevConfidence = 0.99,
            jevFastPathNoul = 0.11,
        ),
        Row(
            id = "f4",
            lang = "ms",
            query = "Bagaimana dengan ini?",
            previous = "Apa kat depan saya?",
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_SCENE_DESCRIBE",
            jevConfidence = 0.82,
            jevFastPathNoul = 0.18,
        ),
        Row(
            id = "f5",
            lang = "zh",
            query = "我面前是什么？",
            previous = null,
            expected = "VLM_SCENE_DESCRIBE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_SCENE_DESCRIBE",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.11,
        ),
        Row(
            id = "f6",
            lang = "zh",
            query = "那这个呢？",
            previous = "我面前是什么？",
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_SCENE_DESCRIBE",
            jevConfidence = 0.75,
            jevFastPathNoul = 0.15,
        ),
        Row(
            id = "f7",
            lang = "en",
            query = "And this one?",
            previous = "What color is this shirt?",
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "FAST_COLOR_ANALYSIS",
            jevConfidence = 0.83,
            jevFastPathNoul = 0.38,
        ),
        Row(
            id = "f8",
            lang = "ms",
            query = "Yang ini pula?",
            previous = "Apa warna baju ini?",
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "VLM_SCENE_DESCRIBE",
            jevConfidence = 0.55,
            jevFastPathNoul = 0.22,
        ),
        Row(
            id = "f9",
            lang = "zh",
            query = "这个呢？",
            previous = "这件衣服是什么颜色？",
            expected = "VLM_VOICE_QUERY",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "FAST_COLOR_ANALYSIS",
            jevConfidence = 0.72,
            jevFastPathNoul = 0.28,
        ),
        Row(
            id = "f10",
            lang = "ms",
            query = "Yang ini juga baca.",
            previous = "Baca label ubat ini.",
            expected = "VLM_TEXT_READ",
            regexAction = "VLM_TEXT_READ",
            jevAction = "VLM_TEXT_READ",
            jevConfidence = 0.99,
            jevFastPathNoul = 0.5,
        ),
        Row(
            id = "f11",
            lang = "en",
            query = "Read this one too.",
            previous = "What does this medicine label say?",
            expected = "VLM_TEXT_READ",
            regexAction = "VLM_TEXT_READ",
            jevAction = "VLM_TEXT_READ",
            jevConfidence = 0.98,
            jevFastPathNoul = 0.39,
        ),
        Row(
            id = "n1",
            lang = "en",
            query = "",
            previous = null,
            expected = "IGNORE",
            regexAction = "IGNORE",
            jevAction = "IGNORE",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.37,
        ),
        Row(
            id = "n2",
            lang = "ms",
            query = "errr... aaa...",
            previous = null,
            expected = "IGNORE",
            regexAction = "VLM_VOICE_QUERY",
            jevAction = "IGNORE",
            jevConfidence = 1.0,
            jevFastPathNoul = 0.59,
        ),
    )

    /** Actions whose speech-routing correctness the gate measures. */
    val GATE_ACTIONS = setOf(
        "VLM_SCENE_DESCRIBE", "VLM_TEXT_READ", "VLM_VOICE_QUERY",
        "FAST_COLOR_ANALYSIS", "LIGHT_CHECK", "SOS", "IGNORE",
    )
}
